export const metadata = {
  title: 'Create Next App sss',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <nav>
        <p>This is nav v2</p>
      </nav>
      {children}
    </>
  );
}
